import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0f',
  },
  contentContainer: {
    flex: 1,
    position: 'relative',
  },
  keyboardAvoidContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0a0a0f',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 10,
    paddingBottom: Platform.OS === 'ios' ? 30 : 10,
    backgroundColor: '#0a0a0f',
    borderTopWidth: 1,
    borderTopColor: 'rgba(96, 165, 250, 0.3)',
  },
  TextThing: {
    flex: 1,
    minHeight: 40,
    maxHeight: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginRight: 10,
    color: 'white',
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#1E90FF',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  messageContainer: {
    padding: 12,
    borderRadius: 16,
    marginVertical: 8,
    maxWidth: '80%',
    backgroundColor: 'rgba(147, 197, 253, 0.1)',
    shadowColor: '#60a5fa',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.3)',
  },
  messageText: {
    color: '#f0f9ff',
    fontSize: 16,
  },
  errorMessage: {
    backgroundColor: '#FF4444',
    padding: 12,
    borderRadius: 12,
    marginVertical: 5,
    maxWidth: '90%',
    alignSelf: 'center',
  },
  errorText: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
  },
  loadingContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 70,
    padding: 10,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  loadingText: {
    color: '#666',
    marginTop: 5,
  },
  limitIndicator: {
    position: 'absolute',
    bottom: 70,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingVertical: 5,
    backgroundColor: 'transparent',
  },
  limitText: {
    color: '#666',
    fontSize: 12,
  },
  header: {
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(96, 165, 250, 0.3)',
  },
  headerTitle: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
  },
  backButtonText: {
    color: '#1E90FF',
    fontSize: 16,
  },
  holographicEffect: {
    shadowColor: '#60a5fa',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  neonText: {
    textShadowColor: '#60a5fa',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
});

export default styles;
